DROP TABLE IF EXISTS SEAT;
CREATE TABLE SEAT(
ID INT AUTO_INCREMENT NOT NULL,
SEAT_NO INT ,
SCREEN_ID INT,
ROW VARCHAR(255),
STATUS VARCHAR(255),
AISLE VARCHAR(255),
PRIMARY KEY (ID));


DROP TABLE IF EXISTS SCREEN;
CREATE TABLE SCREEN(
ID INT AUTO_INCREMENT NOT NULL,
NAME VARCHAR(255),
PRIMARY KEY (ID));
